### ISSUE TITLE
where can I find the training set? 

### ISSUE THREAD

**Issue by nanyyyyyy** [psunlpgroup/MultiHiertt#4]
May I ask where I can find the training set? Thanks!

**Comment by yilunzhao** [comment]
Hi @nanyyyyyy, thank you for your interest in our work and for pointing out this issue. 

It turns out my school Google account recently imposed a 20GB storage limit, which led to the automatic deletion of files larger than 200MB. I’ve reuploaded the training set from my backup at the same Google drive link.

**Comment by nanyyyyyy** [comment]
thanks!
